#!/bin/bash

DIR=$( dirname "$0" )

# Only report every 30 seconds
DETFIL="/tmp/last_motion_detect.ts"
if [ -f "$DETFIL" ]; then
	if test "`find "$DETFIL" -mmin -0,5`"; then
		# Neuer als 30 Sekunden. Nix machen
		exit
	fi
fi
touch "$DETFIL"

# Execute detect.d/*
for i in "$DIR"/detect.d/*; do ( "$i" &) ; done
